import { beforeEach, describe, expect, it, vi } from "vitest";

type SessionsStoreModule = typeof import("@/store/sessionsStore");

/** Stable fake UUIDs for “id does not exist” cases (never generated by the store). */
const UNKNOWN_WORKSPACE_ID = "00000000-0000-4000-8000-000000000099";
const UNKNOWN_SESSION_ID = "00000000-0000-4000-8000-000000000088";

let useSessionStore: SessionsStoreModule["useSessionStore"];

beforeEach(async () => {
	vi.resetModules();
	// creates a brand new store instance for each test
	// since create() runs each time before each test
	// it also creates a workspace with one session with a default cwd of "~"
	({ useSessionStore } = await import("@/store/sessionsStore"));
});

describe("createWorkspace", () => {
	it("appends a workspace, activates it, and copies cwd from the previously active session", () => {
		const before = useSessionStore.getState();
		expect(before.workspaces).toHaveLength(1);
		const firstWs = before.workspaces[0];
		const firstSession = firstWs.sessions[0];

		useSessionStore
			.getState()
			.setCwd(firstSession.id, "~/Projects/Foo/testing");
		useSessionStore.getState().createWorkspace(); // create another workspace

		const after = useSessionStore.getState();
		expect(after.workspaces).toHaveLength(2); // now we have 2 workspaces
		expect(after.activeWorkspaceId).not.toBe(firstWs.id); // the new workspace is activated

		const newWs = after.workspaces.find(
			(w) => w.id === after.activeWorkspaceId,
		);
		expect(newWs).toBeDefined();
		expect(newWs!.sessions).toHaveLength(1); // the new workspace has one session
		expect(newWs!.sessions[0].cwd).toBe("~/Projects/Foo/testing"); // the session has the cwd of the previously active session
	});
});

describe("closeWorkspace", () => {
	it("does nothing when there is only one workspace", () => {
		const before = useSessionStore.getState();
		expect(before.workspaces).toHaveLength(1);
		const id = before.workspaces[0].id;

		useSessionStore.getState().closeWorkspace(id);

		const after = useSessionStore.getState();
		expect(after.workspaces).toHaveLength(1);
		expect(after.workspaces[0].id).toBe(id);
		expect(after.activeWorkspaceId).toBe(id);
	});

	it("removes a non-active workspace and keeps activeWorkspaceId", () => {
		useSessionStore.getState().createWorkspace(); // create another workspace
		const mid = useSessionStore.getState();
		expect(mid.workspaces).toHaveLength(2); // now we have 2 workspaces
		const [first, second] = mid.workspaces;
		expect(mid.activeWorkspaceId).toBe(second.id); // the second workspace is activated

		useSessionStore.getState().closeWorkspace(first.id); // close the first workspace

		const after = useSessionStore.getState();
		expect(after.workspaces).toHaveLength(1); // now we have 1 workspace
		expect(after.workspaces[0].id).toBe(second.id);
		expect(after.activeWorkspaceId).toBe(second.id); // the second workspace is still activated
	});

	it("when closing the active workspace, activates the previous workspace in the list", () => {
		useSessionStore.getState().createWorkspace();
		useSessionStore.getState().createWorkspace();
		const mid = useSessionStore.getState();
		expect(mid.workspaces).toHaveLength(3);
		const [w1, w2, w3] = mid.workspaces;
		expect(mid.activeWorkspaceId).toBe(w3.id); // the third workspace is activated, since it was created last

		useSessionStore.getState().closeWorkspace(w3.id); // close the third workspace

		const after = useSessionStore.getState();
		expect(after.workspaces).toHaveLength(2); // now we have 2 workspaces
		expect(after.workspaces.map((w) => w.id)).toEqual([w1.id, w2.id]);
		expect(after.activeWorkspaceId).toBe(w2.id);
	});

	it("does not remove a workspace when workspaceId is unknown", () => {
		useSessionStore.getState().createWorkspace();
		const before = useSessionStore.getState();
		expect(before.workspaces).toHaveLength(2);

		useSessionStore.getState().closeWorkspace(UNKNOWN_WORKSPACE_ID);

		const after = useSessionStore.getState();
		expect(after.workspaces.map((w) => w.id)).toEqual(
			before.workspaces.map((w) => w.id),
		);
		expect(after.activeWorkspaceId).toBe(before.activeWorkspaceId);
	});
});

describe("activateWorkspace", () => {
	it("sets activeWorkspaceId without changing the workspace list", () => {
		useSessionStore.getState().createWorkspace();
		const mid = useSessionStore.getState();
		const [first, second] = mid.workspaces;
		expect(mid.activeWorkspaceId).toBe(second.id);

		useSessionStore.getState().activateWorkspace(first.id); // activate the first workspace

		const after = useSessionStore.getState();
		expect(after.workspaces.map((w) => w.id)).toEqual([
			first.id,
			second.id,
		]);
		expect(after.activeWorkspaceId).toBe(first.id); // the first workspace is activated
	});

	it("does not change state when workspaceId does not exist", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().activateWorkspace(UNKNOWN_WORKSPACE_ID);
		const after = useSessionStore.getState();
		expect(after.activeWorkspaceId).toBe(before.activeWorkspaceId);
		expect(after.workspaces).toBe(before.workspaces);
	});
});

describe("createSessionInWorkspace", () => {
	it("appends a session, makes it active, and copies cwd from the workspace active tab", () => {
		const { workspaces } = useSessionStore.getState();
		expect(workspaces).toHaveLength(1);
		const ws = workspaces[0];
		const firstTab = ws.sessions[0];
		expect(ws.sessions).toHaveLength(1); // the workspace has one session/terminal
		expect(ws.activeSessionId).toBe(firstTab.id); // the first session/terminal is active

		useSessionStore.getState().setCwd(firstTab.id, "~/repo/app");
		useSessionStore.getState().createSessionInWorkspace(ws.id); // create another session/terminal in the same workspace

		const after = useSessionStore.getState();
		const updated = after.workspaces.find((w) => w.id === ws.id);
		expect(updated).toBeDefined();
		expect(updated!.sessions).toHaveLength(2); // now the workspace has two sessions/terminals
		const newTab = updated!.sessions.find((s) => s.id !== firstTab.id);
		expect(newTab).toBeDefined();
		expect(updated!.activeSessionId).toBe(newTab!.id); // the new session/terminal is active
		expect(newTab!.cwd).toBe("~/repo/app"); // the new session/terminal has the cwd of the previously active session/terminal
	});

	it("does not add a session when workspaceId is unknown", () => {
		const before = useSessionStore.getState();
		const counts = before.workspaces.map((w) => w.sessions.length);

		useSessionStore
			.getState()
			.createSessionInWorkspace(UNKNOWN_WORKSPACE_ID);

		const after = useSessionStore.getState();
		expect(after.workspaces.map((w) => w.sessions.length)).toEqual(counts);
		expect(after.workspaces.map((w) => w.id)).toEqual(
			before.workspaces.map((w) => w.id),
		);
	});
});

describe("closeSession", () => {
	it("no-ops when workspaceId is not found", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().closeSession(
			"00000000-0000-4000-8000-000000000001", // workspace id that does not exist
			before.workspaces[0].sessions[0].id,
		);
		const after = useSessionStore.getState();
		expect(after.workspaces).toBe(before.workspaces);
	});

	it("no-ops when closing the only session of the only workspace", () => {
		const before = useSessionStore.getState();
		const ws = before.workspaces[0];
		useSessionStore.getState().closeSession(ws.id, ws.sessions[0].id);
		const after = useSessionStore.getState();
		expect(after.workspaces).toHaveLength(1);
		expect(after.workspaces[0].id).toBe(ws.id);
		expect(after.workspaces[0].sessions).toHaveLength(1);
	});

	it("closing the only session of a workspace removes that workspace when another exists", () => {
		useSessionStore.getState().createWorkspace();
		const mid = useSessionStore.getState();
		const [first, second] = mid.workspaces;
		const onlyTab = second.sessions[0];
		expect(mid.activeWorkspaceId).toBe(second.id);

		useSessionStore.getState().closeSession(second.id, onlyTab.id);

		const after = useSessionStore.getState();
		expect(after.workspaces).toHaveLength(1);
		expect(after.workspaces[0].id).toBe(first.id);
		expect(after.activeWorkspaceId).toBe(first.id);
	});

	it("does not remove a one-tab workspace when sessionId does not match that tab", () => {
		useSessionStore.getState().createWorkspace();
		const before = useSessionStore.getState();
		const [first, second] = before.workspaces;

		useSessionStore.getState().closeSession(second.id, UNKNOWN_SESSION_ID);

		const after = useSessionStore.getState();
		expect(after.workspaces.map((w) => w.id)).toEqual([
			first.id,
			second.id,
		]);
		expect(after.activeWorkspaceId).toBe(before.activeWorkspaceId);
	});

	it("removes a non-active session and keeps activeSessionId", () => {
		const ws = useSessionStore.getState().workspaces[0];
		const firstTab = ws.sessions[0];
		useSessionStore.getState().createSessionInWorkspace(ws.id);
		const mid = useSessionStore.getState();
		const w = mid.workspaces.find((x) => x.id === ws.id)!;
		const secondTab = w.sessions.find((s) => s.id !== firstTab.id)!;
		expect(w.activeSessionId).toBe(secondTab.id);

		useSessionStore.getState().closeSession(ws.id, firstTab.id);

		const after = useSessionStore.getState();
		const w2 = after.workspaces.find((x) => x.id === ws.id)!;
		expect(w2.sessions).toHaveLength(1);
		expect(w2.sessions[0].id).toBe(secondTab.id);
		expect(w2.activeSessionId).toBe(secondTab.id);
	});

	it("when closing the active session, activates the previous session in that workspace", () => {
		const ws = useSessionStore.getState().workspaces[0];
		const firstTab = ws.sessions[0];
		useSessionStore.getState().createSessionInWorkspace(ws.id);
		const mid = useSessionStore.getState();
		const w = mid.workspaces.find((x) => x.id === ws.id)!;
		const secondTab = w.sessions.find((s) => s.id !== firstTab.id)!;
		expect(w.activeSessionId).toBe(secondTab.id);

		useSessionStore.getState().closeSession(ws.id, secondTab.id);

		const after = useSessionStore.getState();
		const w2 = after.workspaces.find((x) => x.id === ws.id)!;
		expect(w2.sessions).toHaveLength(1);
		expect(w2.sessions[0].id).toBe(firstTab.id);
		expect(w2.activeSessionId).toBe(firstTab.id);
	});

	it("does not remove a session when sessionId is not in that workspace", () => {
		useSessionStore.getState().createWorkspace();
		const mid = useSessionStore.getState();
		const [first, second] = mid.workspaces;
		useSessionStore.getState().createSessionInWorkspace(first.id);
		const mid2 = useSessionStore.getState();
		const f = mid2.workspaces.find((w) => w.id === first.id)!;
		const s = mid2.workspaces.find((w) => w.id === second.id)!;
		const tabInSecond = s.sessions[0];
		const firstTabIds = f.sessions.map((x) => x.id);

		useSessionStore.getState().closeSession(first.id, tabInSecond.id);

		const after = useSessionStore.getState();
		const f2 = after.workspaces.find((w) => w.id === first.id)!;
		const s2 = after.workspaces.find((w) => w.id === second.id)!;
		expect(f2.sessions.map((x) => x.id).sort()).toEqual(
			firstTabIds.slice().sort(),
		);
		expect(s2.sessions.map((x) => x.id)).toEqual([tabInSecond.id]);
	});

	it("does not remove a session when sessionId is unknown (but workspace exists)", () => {
		const ws = useSessionStore.getState().workspaces[0];
		useSessionStore.getState().createSessionInWorkspace(ws.id);
		const mid = useSessionStore.getState();
		const w = mid.workspaces.find((x) => x.id === ws.id)!;
		expect(w.sessions).toHaveLength(2); // the workspace has two sessions/terminals

		useSessionStore.getState().closeSession(ws.id, UNKNOWN_SESSION_ID);

		const after = useSessionStore.getState();
		const w2 = after.workspaces.find((x) => x.id === ws.id)!;
		expect(w2.sessions).toHaveLength(2); // the workspace still has two sessions/terminals
		expect(w2.sessions.map((s) => s.id).sort()).toEqual(
			w.sessions.map((s) => s.id).sort(),
		);
		expect(w2.activeSessionId).toBe(w.activeSessionId); // the active session/terminal is still the same
	});
});

describe("activateSession", () => {
	it("sets the active tab within a workspace and focuses that workspace", () => {
		const ws = useSessionStore.getState().workspaces[0];
		const firstTab = ws.sessions[0];
		useSessionStore.getState().createSessionInWorkspace(ws.id);
		const mid = useSessionStore.getState();
		const w = mid.workspaces.find((x) => x.id === ws.id)!;
		const secondTab = w.sessions.find((s) => s.id !== firstTab.id)!;
		expect(w.activeSessionId).toBe(secondTab.id);

		useSessionStore.getState().activateSession(ws.id, firstTab.id);

		const after = useSessionStore.getState();
		const w2 = after.workspaces.find((x) => x.id === ws.id)!;
		expect(w2.activeSessionId).toBe(firstTab.id);
		expect(after.activeWorkspaceId).toBe(ws.id);
	});

	it("does not change state when workspaceId does not exist", () => {
		const before = useSessionStore.getState();
		const tabId = before.workspaces[0].sessions[0].id;

		useSessionStore.getState().activateSession(UNKNOWN_WORKSPACE_ID, tabId);

		const after = useSessionStore.getState();
		expect(after.activeWorkspaceId).toBe(before.activeWorkspaceId);
		expect(after.workspaces).toBe(before.workspaces);
	});

	it("does not change state when sessionId is not in that workspace", () => {
		useSessionStore.getState().createWorkspace();
		const mid = useSessionStore.getState();
		const [first, second] = mid.workspaces;
		useSessionStore.getState().createSessionInWorkspace(first.id);
		const before = useSessionStore.getState();
		const tabInSecond = before.workspaces.find((w) => w.id === second.id)!
			.sessions[0];

		useSessionStore.getState().activateSession(first.id, tabInSecond.id);

		const after = useSessionStore.getState();
		expect(after.workspaces).toBe(before.workspaces);
		expect(after.activeWorkspaceId).toBe(before.activeWorkspaceId);
	});
});

function initialTab() {
	return useSessionStore.getState().workspaces[0].sessions[0];
}

describe("setCwd", () => {
	it("updates cwd on the matching session", () => {
		const tab = initialTab();
		useSessionStore.getState().setCwd(tab.id, "~/Projects/Blackslate");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!.cwd,
		).toBe("~/Projects/Blackslate");
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setCwd(UNKNOWN_SESSION_ID, "/nope"); // set cwd on a session that does not exist
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces); // the workspaces REFERENCE is the same
	});
});

describe("setGit", () => {
	it("sets git info on the matching session", () => {
		const tab = initialTab();
		const git = { branch: "feature/x", dirty: true };
		useSessionStore.getState().setGit(tab.id, git);
		const sess = useSessionStore
			.getState()
			.workspaces[0].sessions.find((s) => s.id === tab.id)!;
		expect(sess.git).toEqual(git);
	});

	it("clears git when set to null", () => {
		const tab = initialTab();
		useSessionStore.getState().setGit(tab.id, {
			branch: "main",
			dirty: false,
		});
		useSessionStore.getState().setGit(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!.git,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setGit(UNKNOWN_SESSION_ID, {
			branch: "x",
			dirty: false,
		});
		// the workspaces REFERENCE is the same
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setPtyId", () => {
	it("sets ptyId on the matching session", () => {
		const tab = initialTab();
		useSessionStore.getState().setPtyId(tab.id, "pty-abc");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!.ptyId,
		).toBe("pty-abc");
	});

	it("clears ptyId when set to null", () => {
		const tab = initialTab();
		useSessionStore.getState().setPtyId(tab.id, "pty-abc");
		useSessionStore.getState().setPtyId(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!.ptyId,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setPtyId(UNKNOWN_SESSION_ID, "x");
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setClaudeCodeActive", () => {
	it("updates claudeCodeActive on the matching session", () => {
		const tab = initialTab();
		expect(tab.claudeCodeActive).toBe(false);
		useSessionStore.getState().setClaudeCodeActive(tab.id, true);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeCodeActive,
		).toBe(true);
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore
			.getState()
			.setClaudeCodeActive(UNKNOWN_SESSION_ID, true);
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setClaudeState", () => {
	it("updates claudeState on the matching session", () => {
		const tab = initialTab();
		useSessionStore.getState().setClaudeState(tab.id, "thinking");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeState,
		).toBe("thinking");
	});

	it("allows null", () => {
		const tab = initialTab();
		useSessionStore.getState().setClaudeState(tab.id, "complete");
		useSessionStore.getState().setClaudeState(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeState,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore
			.getState()
			.setClaudeState(UNKNOWN_SESSION_ID, "waiting");
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setClaudeSessionTitle", () => {
	it("updates claudeSessionTitle on the matching session", () => {
		const tab = initialTab();
		useSessionStore
			.getState()
			.setClaudeSessionTitle(tab.id, "Refactor store");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeSessionTitle,
		).toBe("Refactor store");
	});

	it("clears title when set to null", () => {
		const tab = initialTab();
		useSessionStore.getState().setClaudeSessionTitle(tab.id, "T");
		useSessionStore.getState().setClaudeSessionTitle(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeSessionTitle,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore
			.getState()
			.setClaudeSessionTitle(UNKNOWN_SESSION_ID, "nope");
		// the workspaces REFERENCE is the same
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setClaudeModel", () => {
	it("updates claudeModel on the matching session", () => {
		const tab = initialTab();
		useSessionStore.getState().setClaudeModel(tab.id, "claude-3-5-sonnet");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeModel,
		).toBe("claude-3-5-sonnet");
	});

	it("clears model when set to null", () => {
		const tab = initialTab();
		useSessionStore.getState().setClaudeModel(tab.id, "m");
		useSessionStore.getState().setClaudeModel(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.claudeModel,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setClaudeModel(UNKNOWN_SESSION_ID, "x");
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setSessionCustomName", () => {
	it("stores a trimmed custom name", () => {
		const tab = initialTab();
		useSessionStore.getState().setSessionCustomName(tab.id, "  My tab  ");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.customName,
		).toBe("My tab");
	});

	it("clears customName for null, empty string, or whitespace-only", () => {
		const tab = initialTab();
		useSessionStore.getState().setSessionCustomName(tab.id, "Named");
		useSessionStore.getState().setSessionCustomName(tab.id, "");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.customName,
		).toBeNull();

		useSessionStore.getState().setSessionCustomName(tab.id, "N2");
		useSessionStore.getState().setSessionCustomName(tab.id, "   ");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.customName,
		).toBeNull();

		useSessionStore.getState().setSessionCustomName(tab.id, "N3");
		useSessionStore.getState().setSessionCustomName(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.customName,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore
			.getState()
			.setSessionCustomName(UNKNOWN_SESSION_ID, "ghost");
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setShellState", () => {
	it("updates shellState on the matching session", () => {
		const tab = initialTab();
		useSessionStore.getState().setShellState(tab.id, "running");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.shellState,
		).toBe("running");
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setShellState(UNKNOWN_SESSION_ID, "running");
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setCurrentTool", () => {
	it("updates currentTool on the matching session", () => {
		const tab = initialTab();
		useSessionStore.getState().setCurrentTool(tab.id, "Reading foo.ts");
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.currentTool,
		).toBe("Reading foo.ts");
	});

	it("clears currentTool when set to null", () => {
		const tab = initialTab();
		useSessionStore.getState().setCurrentTool(tab.id, "t");
		useSessionStore.getState().setCurrentTool(tab.id, null);
		expect(
			useSessionStore
				.getState()
				.workspaces[0].sessions.find((s) => s.id === tab.id)!
				.currentTool,
		).toBeNull();
	});

	it("does not change workspaces when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setCurrentTool(UNKNOWN_SESSION_ID, "x");
		expect(useSessionStore.getState().workspaces).toBe(before.workspaces);
	});
});

describe("setLastTurnUsage", () => {
	it("sets lastTurnUsage and copies cumulativeUsage when there was no prior cumulative", () => {
		const tab = initialTab();
		const usage = {
			inputTokens: 10,
			outputTokens: 4,
			cacheRead: 2,
			cacheWrite: 1,
		};
		useSessionStore.getState().setLastTurnUsage(tab.id, usage);
		const sess = useSessionStore
			.getState()
			.workspaces[0].sessions.find((s) => s.id === tab.id)!;
		expect(sess.lastTurnUsage).toEqual(usage);
		expect(sess.cumulativeUsage).toEqual(usage);
	});

	it("adds onto cumulativeUsage on subsequent turns", () => {
		const tab = initialTab();
		const first = {
			inputTokens: 10,
			outputTokens: 5,
			cacheRead: 1,
			cacheWrite: 2,
		};
		const second = {
			inputTokens: 3,
			outputTokens: 1,
			cacheRead: 4,
			cacheWrite: 0,
		};
		useSessionStore.getState().setLastTurnUsage(tab.id, first);
		useSessionStore.getState().setLastTurnUsage(tab.id, second);
		const sess = useSessionStore
			.getState()
			.workspaces[0].sessions.find((s) => s.id === tab.id)!;
		expect(sess.lastTurnUsage).toEqual(second);
		expect(sess.cumulativeUsage).toEqual({
			inputTokens: 13,
			outputTokens: 6,
			cacheRead: 5,
			cacheWrite: 2,
		});
	});

	it("clears lastTurnUsage when set to null without resetting cumulativeUsage", () => {
		const tab = initialTab();
		const usage = {
			inputTokens: 1,
			outputTokens: 1,
			cacheRead: 0,
			cacheWrite: 0,
		};
		useSessionStore.getState().setLastTurnUsage(tab.id, usage);
		useSessionStore.getState().setLastTurnUsage(tab.id, null);
		const sess = useSessionStore
			.getState()
			.workspaces[0].sessions.find((s) => s.id === tab.id)!;
		expect(sess.lastTurnUsage).toBeNull();
		expect(sess.cumulativeUsage).toEqual(usage);
	});

	it("does not change state when sessionId is unknown", () => {
		const before = useSessionStore.getState();
		useSessionStore.getState().setLastTurnUsage(UNKNOWN_SESSION_ID, {
			inputTokens: 1,
			outputTokens: 0,
			cacheRead: 0,
			cacheWrite: 0,
		});
		const after = useSessionStore.getState();
		// the workspaces REFERENCE is the same
		expect(after.workspaces).toBe(before.workspaces);
	});
});

describe("setWorkspaceCustomName", () => {
	it("stores a trimmed workspace custom name", () => {
		const ws = useSessionStore.getState().workspaces[0];
		useSessionStore
			.getState()
			.setWorkspaceCustomName(ws.id, "  Side project  ");
		expect(
			useSessionStore.getState().workspaces.find((w) => w.id === ws.id)!
				.customName,
		).toBe("Side project");
	});

	it("clears customName for null, empty string, or whitespace-only", () => {
		const ws = useSessionStore.getState().workspaces[0];
		useSessionStore.getState().setWorkspaceCustomName(ws.id, "Named");
		useSessionStore.getState().setWorkspaceCustomName(ws.id, "");
		expect(
			useSessionStore.getState().workspaces.find((w) => w.id === ws.id)!
				.customName,
		).toBeNull();

		useSessionStore.getState().setWorkspaceCustomName(ws.id, "N2");
		useSessionStore.getState().setWorkspaceCustomName(ws.id, "   ");
		expect(
			useSessionStore.getState().workspaces.find((w) => w.id === ws.id)!
				.customName,
		).toBeNull();

		useSessionStore.getState().setWorkspaceCustomName(ws.id, "N3");
		useSessionStore.getState().setWorkspaceCustomName(ws.id, null);
		expect(
			useSessionStore.getState().workspaces.find((w) => w.id === ws.id)!
				.customName,
		).toBeNull();
	});

	it("does not change any workspace customName when workspaceId is unknown", () => {
		useSessionStore.getState().createWorkspace();
		const before = useSessionStore.getState();
		const namesBefore = before.workspaces.map((w) => w.customName);

		useSessionStore
			.getState()
			.setWorkspaceCustomName(UNKNOWN_WORKSPACE_ID, "ghost");

		const after = useSessionStore.getState();
		expect(after.workspaces.map((w) => w.customName)).toEqual(namesBefore);
	});
});
